work_dir: ./work_dir/ntu60/xview/tcagcn_joint

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: /mnt/data/NTU60_CV.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: True
  bone: True

test_feeder_args:
  data_path: /mnt/data/NTU60_CV.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: True
  bone: True
  debug: False

# model
model: model.tcagcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0003
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: [0,2]
batch_size: 64
test_batch_size: 64
num_epoch: 75
nesterov: True
